services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: io-service
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped

  io-service:
    container_name: io-service
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "10000:${IO_SERVICE_PORT}"

volumes:
  postgres: